
DELETE FROM LIVRO_ASSUNTO;
DELETE FROM LIVRO_AUTOR;
DELETE FROM AUTOR;
DELETE FROM ASSUNTO;
DELETE FROM LIVRO;

INSERT INTO AUTOR(NOME)
VALUES('FULANO');

INSERT INTO AUTOR(NOME)
VALUES('BELTRANO');

INSERT INTO AUTOR(NOME)
VALUES('CICLANO');

INSERT INTO ASSUNTO(DESCRICAO)
VALUES('TECNOLOGIA');

INSERT INTO ASSUNTO(DESCRICAO)
VALUES('FICÇÃO');

INSERT INTO ASSUNTO(DESCRICAO)
VALUES('FANTASIA');

INSERT INTO ASSUNTO(DESCRICAO)
VALUES('AUTO AJUDA');
