apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-backend-books
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-backend-books
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50