apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-backend-books
  labels:
    app: api-backend-books
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-backend-books
  template:
    metadata:
      labels:
        app: api-backend-books
    spec:
      containers:
        - name: api-backend-books
          image: kalatunga/api-backend-books
          resources:
            requests:
              memory: "250Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: api-backend-books
  labels:
    app: api-backend-books
spec:
  ports:
    - port: 8090
      protocol: TCP
      nodePort: 31000
  selector:
    app: api-backend-books
  type: NodePort